EY-1832: Bytt ut nav-frontend med ds-react/css/icons
navikt/pensjon-etterlatte pull request #328
Opened 2023-03-10 08:33 UTC by emilps

2023-03-10 09:35 UTC, Watercolours approved these changes
Nice! Synes det ser bra ut, men siden det er så mange endringer tenker jeg det er lurt å deploye til dev og få 1-2 personer til å gå over for å sjekke at alt fungerer som det skal.

2023-03-10 09:35 UTC, Watercolours commented on apps/gjenlevendepensjon-ui/.eslintrc.yml
> +     'react/no-children-prop': 'off'
Ville kanskje ikke fjernet denne. Er der for å unngå at man gjør en blemme med children. 

Si du har noe à la `<CheckboxGroup children={checkboxes}>{noeInnholdHer}</CheckboxGroup>`... 
I dette tilfellet vil `props.children` være `{noeInnholdHer}` og man mister listen med checkboxes som er sendt inn.

2023-03-10 09:35 UTC, Watercolours commented on apps/gjenlevendepensjon-ui/src/components/felles/StyledComponents.tsx
> +export {}
?

2023-03-10 09:35 UTC, Watercolours commented on apps/gjenlevendepensjon-ui/src/typer/bredde.ts
> +    L = 60
Bredde L brukes aldri

2023-03-10 09:35 UTC, Watercolours commented on apps/gjenlevendepensjon-ui/src/typer/bredde.ts
> +export {}
?

2023-03-10 09:59 UTC, Watercolours requested changes
Har testet litt i dev. Det er en ganske alvorlig feil som oppstår nå. Uansett om man søker barnepensjon sendes det aldri en søknad på vegne av barnet. Dette må fikses!

2023-03-13 13:09 UTC, emilps commented
> 

Har lagt til skjemaelement på flere elementer for å skape mer luft i formen. 
Har også lagd mellomrommet mellom "Hvorfor spør vi om dette?"  og innholdet mindre.

2023-03-13 15:14 UTC, Watercolours approved these changes
Gått over koden og testet i dev. Ser ut til å fungere som det skal nå. 👍

2023-03-15 08:42 UTC, emilps commented
Koden er testet av Wenche og søknaden sendes til korrekt saksbehandlingssystem.

2023-03-15 08:43 UTC, merged